# Generated by Django 6.0.3 on 2026-04-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='repeat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='repeat_interval_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
